**1. What are data structure and why are they important?**
   
   Data structure are ways of orgainizing data and efficiently storing data so that it can be accessed and modified quickly.

**2.Explain difference between mutable and immutable data types with examples.**

   Mutable datatypes are type of data whose initial state can be modified like list,set and dictonaries.

   Immutable dataypes are type of dat whose inital state can't be modified like String and Tuples.

**3.What are the main differnece between lists and tuples in python?**

   Lists are orderd collection of indexable data which can store non homogenous data. Lists are also mutable, meaning we can add , remove or modify elements in lists.

   Tuples are ordered collections of indeable data which can store non homogenous datas, but they are immutable means we can't perform add,remove or modify operations on tuples element.

**4.Describe how dictonary store data?**
    
   Dictonary stores data as an key value pair, It can also store non homogenous datas as an ordered collection where key elements are always unique.

**5.Why you might use set instead of a list in python?**
    
   Sets are unorder collection of unique elements , so in case you don't want to store duplicate elements and order in which they store are not important we use set in place of list. Like employee id records.

**6.What is a string in python and how it is different from a list?**

   Strings are immutable in nature , it's collection of characters,and it can't store non homogenous data like list.We also can't modify elelment of string like we can do in list.

**7.How do tuples data integrity in python?**

   As tuples are immutable in nature , hence once data stores in tuples can't be manipulated. Hence any malicious actors can't manipulate the data stores during a transaction and hence it maintain the integrity of the data.

**8.What are hashtable, and how does it relates to dictonaries in python?**
   
   A hashtable stores data as key value pair and uses a hash function to compute an index. Python implemented dictonaries using hash tables in version 3.0. The key elements in dictonaries are unique as it pass through hash function and results an unique hashvalue which are then stores in array.

**9.Can list contain different data type in python?**
   
   Yes lists can contain  non homogenous data type in python. List can be an orderd collection of string,int,float,another list, and tuples.

**10.Explain why strings are immutable in python?**

  Strings are immutable in nature not just in python in any other programming languages like java meaning once String is created it can't be modified and any attempt to modify string will end up creating another string object. But originally created string can't be modified.

**11.What advantages do dictonaries offers over lists for certain tasks?**

   Dictonaries and list serves differnt purpos in data structure. Dictonaries are used to sters data in key value pair , so actually you access values using unique key hence any loolup of elements will be faster in dictonary.Lists are order collection of non homogenous data type which are iterable in nature, but it can' store data in key value pairs. You can use list if the order in which you stores data is important to you.

**12.Describe a scenario where using a tuple would be preferable over a list?**

   If you would like to ensure integrity of a data you should go for a tuple. As tuples are immutable datatype.

**13. How do sets handle duplicate value in python?**
  
   Sets always allow unique entry in pthon and it doesn't entertain duplicate element. Duplicate elements are automatically removed when you create of update a set.

**14. How does the "in" keyword works differently in lists and dictonaries?**
  
   "in" is a memebership operator which checks whether an element exist in list or not wheereas it checks a particular key or value exists in given dictonary or not. As dictonaries keys are hashed index so finding a key using "in" operator will be faster.

**15. Can you modify the element of tupple? Explain why or why not?**

   As you know tuples are immutable in nature hence you can't modify an element of a tuple. You can access the element of a tupple but you can't modify it.

**16. What is nested dictonary, and give an example of it's use case?**

   A nested dictonary is dictonary under dictonary it allows you to store hierarchial or structured data in python. Each value in outer dictonary can itself be another dictonary of key value pairs.Ex:
     access:{
            Alice: ["read","write"]
            Bob: ["read"]
     }

**17. Describe the time complexity of accessing elements in a dictionary?**
   
  As dictonaries stores data in key value pair and each key is passed through a hashfunction which generates a unique index for each key elements. Hence lookup in dictonaries are fast and any element can be accessed at O(1)time complexity.

**18. In what situations are lists preffered over dictonaries?**

   If your requirement is to stored data in orderd collection lists are preferred option.Where you can access data in iterative fashion without any key element.

**19. Why are dicotnaries considered unordered, and how does affect the data retrieval?**

  dictonaries in python are unordered by design because focus was on faster lookup of elements using hashtable without preserving the order of insertion.

**20. Explain the difference between a list and a dictonary in terms of data retrieval?**
   In dictonary datas are key value mapping and it's store the incoming data on key based. Keys are caluclated with the help of hashfunction of a hashtable and hence access is faster.As you access the data with the help of key rather than index.
   lists stored data in orderd fashion in iterative manner on position based. Hence datas are accessed with the help of index and lookup can be time consuming.

In [2]:
#1. Write a code to create a string with your name and print it.

name = "Rakesh"
print(name)

Rakesh

In [3]:
#2. Write a code to find length of the string "Hello World".
str = "Hello Wolrd"
len(str)

11

In [5]:
#3. Write a code to slice the first 3 charecters from a string "Python Programming".

str = "Python Programming"

str[0:3]

'Pyt'

In [6]:
#4. Write a code to convert the string "hello" to uppercase.

str = "hello"
str.upper()

'HELLO'

In [9]:
#5. Write a code to replace the word "apple" with "orange" in the string "I like apple".

str = "I like apple"
str.replace("apple","orange")

'I like orange'

In [10]:
#6. Write a code to create a list with number 1 to 5 and print it.
l1 = [1,2,3,4,5]
print(l1)

[1, 2, 3, 4, 5]

In [13]:
#7. Write a code to append number 10 to the list [1,2,3,4].

l1 = [1,2,3,4]
l1.append(10)
print(l1)

[1, 2, 3, 4, 10]

In [14]:
#8. Write a code to remove number 3 from the list [1,2,3,4,5]

l1 = [1,2,3,4,5]
l1.remove(3)
print(l1)

[1, 2, 4, 5]

In [15]:
#9. Write a code to access second element in the list ['a','b','c','d']

l1 = ['a','b','c','d']
l1[1]

'b'

In [18]:
#10. Write a code to reverse the list [10,20,30,40,50].

l1 = [10,20,30,40,50]
l1[::-1]

[50, 40, 30, 20, 10]

In [19]:
#11. Write a code to create a tuple with the element 100,200,300 and print it

t = (100,200,300)
print(t)

(100, 200, 300)

In [21]:
#12. Write a code to access the second to last element of the tuple ('red','green','blue','yellow').

t = ('red','green','blue','yellow')
t[-2]

'blue'

In [22]:
#13. Write a code to find the minimum number in the tuple (10,20,5,15).

t = (10,20,5,15)
min(t)

5

In [23]:
#14. Write a code to find the index of element 'cat' in tuple ('dog','cat','rabbit').

t = ('dog','cat','rabbit')
t.index('cat')

1

In [24]:
#15. Write a code to create a tuple with 3 different fruits and check if 'kiwi' is in it.

t = ('apple','banana','kiwi')

if 'kiwi' in t:
  print("kiwi is present in tuple")

kiwi is present in tuple

In [25]:
#16. Write a code to create a set with the element 'a','b','c' and print it.

s = {'a','b','c'}
print(s)

{'b', 'a', 'c'}

In [27]:
#17. Write a code to clear all element from the set {1,2,3,4,5}.

s = {1,2,3,4,5}
s.clear()
print(s)

set()

In [31]:
#18. Write a code to remove the element 4 from the set {1,2,3,4}.

s = {1,2,3,4}
s.remove(4)
print(s)

{1, 2, 3}

In [34]:
#19 Write a code to find the union of 2 sets {1,2,3} and {3,4,5}.

s1 = {1,2,3}
s2 = {3,4,5}
union_set = s1.copy()
for ele in s2:
  union_set.add(ele)
print(union_set)

{1, 2, 3, 4, 5}

In [37]:
#20. Write a code to find the intersection of 2 sets {1,2,3} and {2,3,4}

s1 = {1,2,3}
s2 = {2,3,4}
intersection_Set = set()
for ele in s1:
  if ele in s2:
    intersection_Set.add(ele)

print(intersection_Set)

{2, 3}

In [38]:
#21. Write a code to create a dictonary with key "name","age" and "city", and print it.

d = {"name":"rakesh","age":92,"city":"bangalore"}

print(d)

{'name': 'rakesh', 'age': 92, 'city': 'bangalore'}

In [39]:
#22. Write a code to add a new key-value pair "country":"USA" to the dictonary {'name':'John','age':25}.

d = {'name':'John','age':25}
d['country'] = 'USA'
print(d)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [40]:
#23. Write a code to access the value associated with key "name" in the dictonary {'name':'Alice','age':30}.

d = {'name':'Alice','age':30}
d['name']

'Alice'

In [43]:
#24. Write a code to remove key 'age' from the dictonary {'name':'Bob','age':22,'city':'Paris'}.

d = {'name':'Bob','age':22,'city':'Paris'}
del d['age']
print(d)

{'name': 'Bob', 'city': 'Paris'}

In [45]:
#25. Write a code to check if the key 'city' exist in the dictonary {'name':'Alice','city':'Paris'}.

d = {'name':'Alice','city':'Paris'}
for key in d.keys():
  if key == 'city':
    print(f"'city' key exists in the dictonary")

'city' key exists in the dictonary

In [47]:
#26. Write a code to create a list,a tuple, and a dictonary and print them all

l = [1,2,3]
t = (3,4,5)
d = {'a':1,'b':2,'c':3}
print(f"{l},{t} and {d}")

[1, 2, 3],(3, 4, 5) and {'a': 1, 'b': 2, 'c': 3}

In [52]:
#27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order and print the result.

import random

l1 = [random.randint(1,100) for i in range(5)]
l1.sort()
print(l1)

[34, 40, 56, 62, 71]

In [53]:
#28. Write a code to create a list with string and print the element at third index.

l = ['apple','banana','kiwi','orange','mango']
l[3]

'orange'

In [54]:
#29. Write a code to combine two dictonaries in to one and print it.

d1 = {'name':'Alice','city':'Paris'}
d2 = {'a':1,'b':2,'c':3}
d1.update(d2)
print(d1)

{'name': 'Alice', 'city': 'Paris', 'a': 1, 'b': 2, 'c': 3}

In [55]:
#30. Write a code to convert a list of string into a set.

l = ['apple','banana','kiwi','orange','mango']
s = set(l)
print(s)

{'kiwi', 'mango', 'apple', 'orange', 'banana'}